<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
	'Contact' => '联系我们',
	'Login' => '登录',
	'Logout' => '退出',
	'About' => '关于',
	'Home' => '首页',
	'Post' => '文章',
	'UserName' => '用户名',
	'PassWord' => '密&nbsp;&nbsp;&nbsp;&nbsp码',
	'VerifyCode' => '验证码',	  
	'Username is exists' =>'用户名已经存在',
	'Username is required' => '用户名不能为空',
	'Password is required' => '密码不能为空',
	'Email is required' => '邮箱不能为空',
	'Incorrect username or password.'=>'用户名或密码错误',
	'Login Success' => '登录成功',	
	'Image' => '图片',
	'Submit' => '提交',	
	'Url' => '链接地址',	
	'Email' => '邮箱',
	'Status' => '状态',
	'Normal' => '正常',
	'Locked' => '锁定',
	'Add Success' => '添加成功',
	'Redirect Url' => '跳转地址',
	'Access Deny' => '您无权访问',
);
