<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
	'Contact' => '联系我们',
	'Login' => '登录',
	'Logout' => '退出',
	'About' => '关于',
	'Home' => '首页',
	'Post' => '文章',
	'UserName' => '用户名',
	'PassWord' => '密&nbsp;&nbsp;&nbsp;&nbsp码',
	'VerifyCode' => '验证码',	  
	'Username is exists' =>'用户名已经存在',
	'Email Is Exist' => '邮箱已被注册',
	'Email Format Is Wrong' => '邮箱格式不正确',
	'Username is required' => '用户名不能为空',
	'Password is required' => '密码不能为空',
	'username length is between 6 and 40' => '用户名长度介于6~40个字符',
	'password length is between 6 and 30' => '密码长度介于6~30个字符',
	'Email is required' => '邮箱不能为空',
	'Existing Email' => '邮箱已被使用',
	'Incorrect username or password.'=>'用户名或密码错误',
	'Login Success' => '登录成功',	
	'Image' => '图片',
	'Submit' => '提交',	
	'Url' => '链接地址',	
	'Email' => '邮箱',
	'Status' => '状态',
	'Normal' => '正常',
	'Locked' => '锁定',
	'Add Success' => '添加成功',
	'Redirect Url' => '跳转地址',
	'Access Deny' => '您无权访问',
	'User Center' => '用户中心',
	'Register Email'=>'<p>尊敬的新用户：{username} 您好，欢迎注册{sitename}，为了更好的为您服务，请尽快点击下面链接进行账号激活：<br/><br/>
						<a href="{authurl}">{authurl}</a><br/><br/>(如果上面链接不能点击，请复制到浏览器地址栏中进行访问。)<br/><br/>
						==================<br/><br/>再次感谢您的光顾，如果有其他疑问，
						请联系本网站的管理员：<a href="mailto:{admin_email}">{admin_email}</a>。</p>',
	'Edit User' => '编辑资料',
);
