<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
	'Contact' => '联系我们',
	'Login' => '登录',
	'Logout' => '退出',
	'About' => '关于',
	'Home' => '首页',
	'Post' => '文章',
	'UserName' => '用户名',
	'PassWord' => '密&nbsp;&nbsp;&nbsp;&nbsp码',
	'VerifyCode' => '验证码',	  
	'Username is exists' =>'用户名已经存在',
	'Email Is Exist' => '邮箱已被注册',
	'Email Format Is Wrong' => '邮箱格式不正确',
	'Username is required' => '用户名不能为空',
	'Password is required' => '密码不能为空',
	'username length is between 6 and 40' => '用户名长度介于6~40个字符',
	'password length is between 6 and 30' => '密码长度介于6~30个字符',
	'Email is required' => '邮箱不能为空',
	'Existing Email' => '邮箱已被使用',
	'Incorrect username or password.'=>'用户名或密码错误',
	'Login Success' => '登录成功',	
	'Image' => '图片',
	'Submit' => '提交',	
	'Url' => '链接地址',	
	'Email' => '邮箱',
	'Status' => '状态',
	'Normal' => '正常',
	'Locked' => '锁定',
	'Add Success' => '添加成功',
	'Redirect Url' => '跳转地址',
	'Access Deny' => '您无权访问',
	'User Center' => '用户中心',
	'Register Email'=>'<p>尊敬的新用户：{username} 您好，欢迎注册{sitename}，为了更好的为您服务，请尽快点击下面链接进行账号激活：<br/><br/>
						<a href="{authurl}">{authurl}</a><br/><br/>(如果上面链接不能点击，请复制到浏览器地址栏中进行访问。)<br/><br/>
						==================<br/><br/>再次感谢您的光顾，如果有其他疑问，
						请联系本网站的管理员：<a href="mailto:{admin_email}">{admin_email}</a>。</p>',
	//个人中心 用户设置
	'User Setting' => '用户设置',
	'My Avatar' => '我的头像',
	'Edit' => '编辑',
	'Save' => '保存',
	'Base Profile' => '基本资料',
	'Upload Avatar' => '上传头像',
	'Avatar Size Should Be Less 1M'=>'仅支持JPG,PNG,GIF,BMP格式的图片,<br/>大小不超过1M。',
	'File Uploading' => '文件上传中...',
	'Upload Success' => '上传成功',
	'Cut Success' => '剪切成功',
	'Submit Cut'=>'确认剪切',
	'Upload More Than' =>'上传文件大小超过',
	'Upload Only'=>'只允许上传：',
	'Format File'=>'格式的文件',
	'Only One'=>'只能上传一张图片，请刷新页面后更换',
	'Upload Error' => '上传错误：',
	'Please Select Cut Area'=>'请选择剪切区域再提交',
	'Please Upload Image' => '请上传一个图片',
	'You Should Install Flash' =>'您未安装FLASH控件，无法上传！请先安装FLASH控件后再试。',
	'Setting Email' => '邮箱修改',
	'Setting Pwd' => '密码修改',
	'Upload Image' => '上传图片',
	'Mobile Is Invalid' => '请输入有效的手机号码',
	'Web Is Invalid' => '请输入有效的网址(带http://)',
);
